"""Letter listening reference (the "Letters" page).

The learner picks a letter and hears it. The engine plays a short
sequence of phonetic anchor + morse pairs, then bare morse repeats —
audio recognition for a letter the learner finds tricky. This is
*reference*, not an exercise: there is no scoring, no grading, no
correctness feedback (spec §9). The interface gets out of the way and
lets the ear do the work.

The phonetic anchor is the spec §2.6 NATO recording (e.g. "alpha"
spoken aloud); the morse is generated by :mod:`copy_653.audio.synth`
at the configured tone, speed, and amplitude. Both play through the
engine's audio output so there is one volume control and one routing
path (spec §1.4).
"""

from copy_653.letters.sequence import (
    ANCHORED_SYMBOLS,
    LettersConfig,
    NATO_PHONETIC_NAMES,
    find_anchors_dir,
    play_letter_sequence,
)
from copy_653.letters.wav import load_wav

__all__ = [
    "ANCHORED_SYMBOLS",
    "LettersConfig",
    "NATO_PHONETIC_NAMES",
    "find_anchors_dir",
    "load_wav",
    "play_letter_sequence",
]
